@host = localhost
@port = 8080
@root =
@accessToken = eyJhbGciOiJFZERTQSJ9.eyJleHAiOjEuNzg2NjA5MTgxNjc3MTM0MTc4ZTksImlhdCI6MS43ODY2MDg1ODE2NzcxMzQxNzhlOSwiaXNzIjoiYnVzLXRyYWNrZXIiLCJuYmYiOjEuNzg2NjA4NTgxNjc3MTM0MTc4ZTksInN1YiI6ImFkbWluIiwidHR5cCI6ImFjY2VzcyJ9.V3UqIzpB8NwO682WyN-yiKsrvig2avK0gBNCgolmCx5ZAn38X3sX9gKwSFpmAcQkypOeZzFSspF2T9X5qXNHDQ
@refreshToken = eyJhbGciOiJFZERTQSJ9.eyJleHAiOjEuNzg2NjkyNzA4MTYxMDU4NjM0ZTksImlhdCI6MS43ODY2MDYzMDgxNjEwNTg2MzRlOSwiaXNzIjoiYnVzLXRyYWNrZXIiLCJqdGkiOiJlMWQyZTZjYS03MGNjLTRkMjMtYTY0Mi0zYmQ5ZTQxODZlZmUiLCJuYmYiOjEuNzg2NjA2MzA4MTYxMDU4NjM0ZTksInN1YiI6ImFkbWluIiwidHR5cCI6InJlZnJlc2gifQ.1Kr8QgkukAuDlPgSUhAnJ5HTGASRbEsbHiWgCAAgqg1unIGH1jNI0G_1f1kKzGEf78PoRNYK3G7YLQfPq8-pDA

### Login

POST http://{{host}}:{{port}}{{root}}/auth/login
Content-Type: application/json

{
  "account": "admin",
  "password": "passwordpassword"
}

### Logout

POST http://{{host}}:{{port}}{{root}}/auth/logout
Cookie: accessToken={{accessToken}};refreshToken={{refreshToken}}
