@host = localhost
@port = 8080
@root =
@accessToken = eyJhbGciOiJFZERTQSJ9.eyJleHAiOjEuNzg2NjA5MTgxNjc3MTM0MTc4ZTksImlhdCI6MS43ODY2MDg1ODE2NzcxMzQxNzhlOSwiaXNzIjoiYnVzLXRyYWNrZXIiLCJuYmYiOjEuNzg2NjA4NTgxNjc3MTM0MTc4ZTksInN1YiI6ImFkbWluIiwidHR5cCI6ImFjY2VzcyJ9.V3UqIzpB8NwO682WyN-yiKsrvig2avK0gBNCgolmCx5ZAn38X3sX9gKwSFpmAcQkypOeZzFSspF2T9X5qXNHDQ
@refreshToken = eyJhbGciOiJFZERTQSJ9.eyJleHAiOjEuNzg2NzcyMzM2NTY3Nzg4NTYyZTksImlhdCI6MS43ODY2ODU5MzY1Njc3ODg1NjJlOSwiaXNzIjoiYnVzLXRyYWNrZXIiLCJqdGkiOiI1ZWFmYzdlOS0wN2IwLTQzZWYtOWY2Zi00MGY5NDY5MzMwZDIiLCJuYmYiOjEuNzg2Njg1OTM2NTY3Nzg4NTYyZTksInN1YiI6ImFkbWluIiwidHR5cCI6InJlZnJlc2gifQ.sWcAgfumVBzVFu5dV4ESDQeC1_vKxx9mI-XMwYr6cBXCunzIsWrds8ubD2j7fxPg1Pb0s3W1Qx2oAhvWIB4RAQ

### Login

POST http://{{host}}:{{port}}{{root}}/auth/login
Content-Type: application/json

{
  "account": "admin",
  "password": "passwordpassword"
}

### Logout

POST http://{{host}}:{{port}}{{root}}/auth/logout
Cookie: accessToken={{accessToken}};refreshToken={{refreshToken}}

### Refresh

POST http://{{host}}:{{port}}{{root}}/auth/refresh
Cookie: refreshToken={{refreshToken}}
