@host = localhost
@port = 8080
@root =

### Register user

POST http://{{host}}:{{port}}{{root}}/users
Content-Type: application/json

{
  "account": "admin",
  "password": "passwordpassword"
}

### Get user

GET http://{{host}}:{{port}}{{root}}/users
Cookie: accessToken=eyJhbGciOiJFZERTQSJ9.eyJleHAiOjEuNzg1NTc3MTYxMTgyMDAzOTMzZTksImlhdCI6MS43ODU0OTA3NjExODIwMDM5MzNlOSwiaXNzIjoiYnVzLXRyYWNrZXIiLCJqdGkiOiJiNzA4Yzg2Yy0xN2JkLTRkOGEtYTg2YS1jNzhlZDI4OTQ5OGUiLCJuYmYiOjEuNzg1NDkwNzYxMTgyMDAzOTMzZTksInN1YiI6ImFkbWluIiwidHR5cCI6InJlZnJlc2gifQ.KNxyaMIaj8wVWug55d-Xh5QxaUrOaVkrCmJqcIZbzGvjptWYDDR6ueDTc_5QPZNgfeWNL0d475LmKDPLJl11Cw
