@host = localhost
@port = 8080
@root =

### Register user

POST http://{{host}}:{{port}}{{root}}/users
Content-Type: application/json

{
  "account": "admin",
  "password": "passwordpassword"
}

### Get user

GET http://{{host}}:{{port}}{{root}}/users
Cookie: accessToken=eyJhbGciOiJFZERTQSJ9.eyJleHAiOjEuNzg2NjA2OTA4MTYxMDQxODAyZTksImlhdCI6MS43ODY2MDYzMDgxNjEwNDE4MDJlOSwiaXNzIjoiYnVzLXRyYWNrZXIiLCJuYmYiOjEuNzg2NjA2MzA4MTYxMDQxODAyZTksInN1YiI6ImFkbWluIiwidHR5cCI6ImFjY2VzcyJ9.d0gBh4hPvdOfRu3ZCxrfR-pyao_x3BaW924MBd9oFuWalGDivMVtuIJT4eIDSOL3rDTh-2S4Yoa3fq55CzC-Bg
